[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hydrogenase-feature-extractor"                          
version = "0.0.1"
description = "Script that allows to extract relevant information from NiFe Hydrogenases"                   
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE" }
authors = [
    { name = "Jan-Niklas Forster" }
]
keywords = ["bioinformatics", "structure", "hydrogenases"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

dependencies = [
    "platformdirs==4.11.7",
    "PyYAML==6.0.3",
    "pycaver @ git+https://github.com/jan-fors/pycaver.git",
    "Bio==1.8.3",
    "biopython==1.88",
    "numpy==2.5.2",
]

[project.scripts]
extract-hyd-features = "hydrogenase_feature_extractor.cli:entry"

[tool.setuptools.packages.find]
where = ["."]
include = ["hydrogenase_feature_extractor*"]    

[project.urls]
Repository = "https://github.com/jan-fors/hydrogenase-feature-extractor"                   
